analyzer:
  exclude:
    - legacy/**

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_returning_null_for_void

dcm:
  exclude:
    metrics:
      - test/**
      - .dart_tool/**
      - build/**
      - "**/*.g.dart"
      - "**/*.freezed.dart"
      - "**/*.mocks.dart"

  rules:
    - avoid-dynamic
    - avoid-unused-parameters:
        ignore-inline-functions: true
    - avoid-non-null-assertion:
        skip-checked-fields: true
    - avoid-unrelated-type-assertions
    - avoid-unnecessary-type-assertions
    - avoid-collection-methods-with-unrelated-types:
        strict: true
    - avoid-misused-set-literals
    - avoid-missed-calls
    - avoid-commented-out-code:
        min-lines: 2
    - prefer-commenting-analyzer-ignores:
        ignore-global: true
    - avoid-global-state
    - missing-test-assertion

  metrics:
    cyclomatic-complexity:
      threshold: 10
    maximum-nesting-level:
      threshold: 4
    number-of-parameters:
      threshold: 4
    source-lines-of-code:
      threshold: 40
    number-of-methods:
      threshold: 10
    number-of-imports:
      threshold: 10
    number-of-external-imports:
      threshold: 5
    weighted-methods-per-class:
      threshold: 35
    coupling-between-object-classes:
      threshold: 12
    response-for-class:
      threshold: 40
    depth-of-inheritance-tree:
      threshold: 4
