from __future__ import annotations

import re
from pathlib import Path

from design_lint_model import DesignSchema


def _schema(repository_root: Path) -> DesignSchema:
    patterns = {
        "source": r"^S-[0-9]{3}$",
        "evidence": r"^E-[0-9]{3}$",
        "requirement": r"^R-[0-9]{3}$",
        "form": r"^F-[0-9]{3}$",
        "material_obligation": r"^M-[0-9]{3}$",
        "pressure": r"^P-[0-9]{3}$",
        "decision": r"^D-[0-9]{3}$",
        "assurance": r"^A-[0-9]{3}$",
        "impact": r"^I-[0-9]{3}$",
        "guard": r"^H-[0-9]{3}$",
        "diagram": r"^DG-[0-9]{3}$",
        "blocker": r"^B-[0-9]{3}$",
    }
    core_gates = [
        "Owner-Level Fix",
        "Ownership",
        "Source-Of-Truth Singularity",
        "Source-Truth Minimality",
        "Boundary-Owned Policy",
        "Dependency Direction",
        "Solution Proportionality",
        "Outcome-Proof Fit",
        "Verification",
        "Future Pressure",
        "Handoff Consumability",
    ]
    conditional_gates = [
        "Negative Proof And Fixture Quarantine",
        "State/Data Ownership",
        "Sequenced Migration And Retirement",
        "Temporal Surface Closure",
        "All-Or-Nothing Failure Boundary",
        "Bounded Recognition Scope",
    ]
    architecture_concerns = [
        "owner",
        "in_scope",
        "out_of_scope",
        "source_of_truth",
        "compatibility",
        "order",
        "policy",
        "dependency",
        "state_data",
        "migration_retirement",
        "temporal",
        "atomicity",
        "negative_proof_fixture",
        "recognition",
    ]
    raw: dict[str, object] = {
        "sections": {
            "order": [
                "Basis",
                "Candidate Analysis",
                "Decision Register",
                "Impact Register",
                "Assurance Register",
                "Stop Conditions",
                "Contract Interface",
                "Diagrams",
                "Readiness Matrix",
                "Open Blockers",
            ],
            "required": {
                "READY_FOR_CONTRACT": [
                    "Basis",
                    "Candidate Analysis",
                    "Decision Register",
                    "Impact Register",
                    "Assurance Register",
                    "Stop Conditions",
                    "Contract Interface",
                    "Diagrams",
                    "Readiness Matrix",
                    "Open Blockers",
                ],
                "BLOCKED": [
                    "Basis",
                    "Candidate Analysis",
                    "Open Blockers",
                ],
                "DESIGN_NOT_REQUIRED": [
                    "Basis",
                    "Candidate Analysis",
                    "Readiness Matrix",
                    "Open Blockers",
                ],
            },
            "optional": {
                "READY_FOR_CONTRACT": [],
                "BLOCKED": [
                    "Decision Register",
                    "Assurance Register",
                    "Diagrams",
                    "Readiness Matrix",
                ],
                "DESIGN_NOT_REQUIRED": ["Diagrams"],
            },
        },
        "basis": {
            "source_kinds": [
                "prior_design",
                "research",
                "plan",
                "user",
                "repository",
                "other",
            ],
            "requirement_kinds": [
                "outcome",
                "constraint",
                "user_decision",
                "repository_rule",
                "exclusion",
            ],
        },
        "candidate": {
            "comparison_values": [
                "two_or_three",
                "single_viable",
                "not_applicable",
                "blocked",
            ],
            "pressure_treatments": ["absorbed", "deferred", "rejected"],
            "yes_no": ["yes", "no"],
        },
        "decision": {
            "concerns": ["form", *architecture_concerns],
            "contract_targets": [
                "classification",
                "owner",
                "scope",
                "source_of_truth",
                "compatibility",
                "order",
                "policy",
                "dependency",
                "state_data",
                "migration_retirement",
                "temporal",
                "atomicity",
                "negative_proof_fixture",
                "recognition",
                "acceptance",
                "evidence",
                "verification",
                "durable_impact",
                "unit_family",
            ],
            "assurance_required_concerns": [
                "owner",
                "source_of_truth",
                "compatibility",
                "order",
                "policy",
                "dependency",
                "state_data",
                "migration_retirement",
                "temporal",
                "atomicity",
                "negative_proof_fixture",
                "recognition",
            ],
            "concern_contract_target_map": {
                "form": ["classification"],
                "owner": ["owner"],
                "in_scope": ["scope"],
                "out_of_scope": ["scope"],
                "source_of_truth": ["source_of_truth"],
                "compatibility": ["compatibility"],
                "order": ["order"],
                "policy": ["policy"],
                "dependency": ["dependency"],
                "state_data": ["state_data"],
                "migration_retirement": ["migration_retirement"],
                "temporal": ["temporal"],
                "atomicity": ["atomicity"],
                "negative_proof_fixture": ["negative_proof_fixture"],
                "recognition": ["recognition"],
            },
        },
        "impact": {
            "fields": [
                "Action",
                "Surface",
                "Required by",
                "Resulting authority",
                "Contract requirement",
            ],
            "actions": ["create", "update", "supersede", "retire", "remove"],
            "none_literal": "None",
        },
        "guard": {
            "fields": ["Trigger", "Invalidates", "Resolution requires"],
        },
        "contract": {
            "fields": [
                "Profile",
                "Obligations",
                "ADR Impact",
                "Sources",
                "Requirements",
                "Commitments",
                "Assurance",
                "Impacts",
                "Stops",
            ],
            "adr_pattern": (
                r"^(?:none|create ADR-[0-9]{4}|"
                r"(?:supersede|retire) ADR-[0-9]{4}"
                r"(?:, ADR-[0-9]{4})*)$"
            ),
        },
        "coverage": {
            "architecture_concerns": architecture_concerns,
            "ready_architecture_statuses": ["closed", "not_applicable"],
            "existing_architecture_statuses": ["already_closed", "not_applicable"],
            "core_gates": core_gates,
            "conditional_gates": conditional_gates,
            "ready_core_status": "pass",
            "ready_conditional_statuses": ["pass", "not_applicable"],
            "existing_core_status": "already_closed",
            "existing_conditional_statuses": ["already_closed", "not_applicable"],
            "blocking_failure_statuses": ["failed", "unresolved"],
            "gate_required_ref_groups": {
                "Owner-Level Fix": [["D"], ["R", "E"]],
                "Ownership": [["D"]],
                "Source-Of-Truth Singularity": [["D"]],
                "Source-Truth Minimality": [["D"], ["M", "F"]],
                "Boundary-Owned Policy": [["D"]],
                "Dependency Direction": [["D"]],
                "Solution Proportionality": [["F"], ["M"], ["R", "E"]],
                "Outcome-Proof Fit": [["A"]],
                "Verification": [["A"]],
                "Future Pressure": [["P", "E"]],
                "Handoff Consumability": [["CONTRACT"]],
                "Negative Proof And Fixture Quarantine": [["D"], ["A"]],
                "State/Data Ownership": [["D"], ["A"]],
                "Sequenced Migration And Retirement": [["D"], ["A"]],
                "Temporal Surface Closure": [["D"], ["A"]],
                "All-Or-Nothing Failure Boundary": [["D"], ["A"]],
                "Bounded Recognition Scope": [["D"], ["A"]],
            },
            "concern_gate_map": {
                "owner": ["Owner-Level Fix", "Ownership"],
                "source_of_truth": [
                    "Source-Of-Truth Singularity",
                    "Source-Truth Minimality",
                ],
                "policy": ["Boundary-Owned Policy"],
                "dependency": ["Dependency Direction"],
                "negative_proof_fixture": ["Negative Proof And Fixture Quarantine"],
                "state_data": ["State/Data Ownership"],
                "migration_retirement": ["Sequenced Migration And Retirement"],
                "temporal": ["Temporal Surface Closure"],
                "atomicity": ["All-Or-Nothing Failure Boundary"],
                "recognition": ["Bounded Recognition Scope"],
            },
        },
        "blocker": {
            "kinds": ["research", "user_decision"],
            "additional_gates": [
                "Source Authority",
                "Candidate Comparison",
                "Disposition",
            ],
            "disposition_kinds_map": {
                "BLOCKED": ["research", "user_decision"],
            },
        },
        "locators": {
            "repository_relative_source_kinds": [
                "prior_design",
                "research",
                "plan",
                "repository",
            ],
            "external_absolute_source_kinds": ["other"],
            "literal_source_locators": {"user": "user request"},
            "evidence_line_pattern": r"^line [1-9][0-9]*$",
            "evidence_range_pattern": r"^lines [1-9][0-9]*-[1-9][0-9]*$",
            "evidence_surface_exceptions": [
                "new_path",
                "generated_output",
                "command_surface",
                "configuration_surface",
            ],
        },
        "forbidden_tokens": {
            "active_tokens": ["TODO", "TBD"],
            "template_markers": {"{{TITLE}}": 1},
            "placeholder_values": ["none", "n/a", "not applicable"],
            "meaningful_fields": {
                "R": ["Open shape"],
                "D": ["Lock", "Open", "Rationale"],
                "A": [
                    "Claim",
                    "Failure",
                    "Oracle",
                    "Proxy risk",
                    "Evidence constraints",
                    "Architecture seam",
                ],
                "I": [
                    "Action",
                    "Surface",
                    "Required by",
                    "Resulting authority",
                    "Contract requirement",
                ],
                "H": ["Trigger", "Resolution requires"],
                "B": ["Need", "Blocks because", "Resolution requires"],
            },
        },
    }
    return DesignSchema(
        source_path=repository_root / "design-artifact-schema.json",
        repository_root=repository_root,
        raw=raw,
        version="architecture-design/v4",
        frontmatter_fields=(
            "schema",
            "date",
            "commit",
            "branch",
            "disposition",
            "outcome",
        ),
        dispositions=(
            "READY_FOR_CONTRACT",
            "BLOCKED",
            "DESIGN_NOT_REQUIRED",
        ),
        id_patterns={name: re.compile(pattern) for name, pattern in patterns.items()},
        vocabulary_route="contract-vocabulary.json",
    )
