import 'src/guardrails/guardrails_runner.dart';

// Invariants enforced by this tool:
// INV:INV-ENG-NO-EXTERNAL-MUTATION
// INV:INV-ENG-WRITE-ONLY-MUTATION
// INV:INV-ENG-TXN-ATOMIC-COMMIT
// INV:INV-ENG-EPOCH-INVALIDATION
// INV:INV-G-PUBLIC-ENTRYPOINTS
// INV:INV-ENG-SAFE-TXN-API
// INV:INV-ENG-INTERACTIVE-RESOLVER-PURITY
// INV:INV-ENG-INTERACTIVE-ARCHITECTURE-BOUNDARY
// INV:INV-ENG-MODEL-ARCHITECTURE-BOUNDARY
// INV:INV-ENG-CONTRACT-ARCHITECTURE-BOUNDARY

Future<void> main(List<String> _) => runGuardrailsTool();
