import 'src/import_boundaries/import_boundaries_runner.dart';

// Invariants enforced by this tool:
// INV:INV-G-LAYER-DAG
// INV:INV-G-LAYER-BOUNDARIES
// INV:INV-ENG-NO-EXTERNAL-MUTATION
// INV:INV-ENG-COMMANDS-NO-PART
// INV:INV-ENG-COMMANDS-NO-SCENE-CONTROLLER
// INV:INV-ENG-COMMANDS-NO-CROSS-IMPORTS
// INV:INV-ENG-INTERNAL-NO-SCENE-CONTROLLER
// INV:INV-ENG-INTERNAL-NO-COMMANDS-IMPORTS
// INV:INV-ENG-SHARED-CONTROLLER-HELPERS
// INV:INV-ENG-VIEW-POINTER-SEMANTICS-BOUNDARY

Future<void> main(List<String> _) => runImportBoundariesTool();
