import 'dart:ui';

import '../contract/transform2d.dart';
import '../public/snapshot.dart';
import 'immutable_collections.dart';

/// Discrete actions emitted by interactive controllers for app-level undo/redo.
enum ActionType {
  /// A node-move command committed by the runtime.
  move,

  /// A marquee selection command committed by the runtime.
  selectMarquee,

  /// A transform command such as rotate, flip, or drag-translate.
  transform,

  /// A delete command affecting one or more nodes.
  delete,

  /// A clear-scene command.
  clear,

  /// A pen stroke command.
  drawStroke,

  /// A highlighter stroke command.
  drawHighlighter,

  /// A line drawing command.
  drawLine,

  /// An eraser command.
  erase,
}

/// A committed action with stable [actionId] and affected [nodeIds].
class ActionCommitted {
  /// Creates an immutable action payload for app-level observers.
  factory ActionCommitted({
    required String actionId,
    required ActionType type,
    required List<NodeId> nodeIds,
    required int timestampMs,
    Map<String, Object?>? payload,
  }) {
    return ActionCommitted._(
      actionId: actionId,
      type: type,
      nodeIds: freezeList<NodeId>(nodeIds),
      timestampMs: timestampMs,
      payload: freezePayloadMap(payload),
    );
  }

  /// Internal const constructor used after freezing payload collections.
  const ActionCommitted._({
    required this.actionId,
    required this.type,
    required this.nodeIds,
    required this.timestampMs,
    required this.payload,
  });

  /// Stable action identifier generated by the runtime (`a0`, `a1`, ...).
  final String actionId;

  /// The semantic category of the committed action.
  final ActionType type;

  /// Immutable snapshot of affected node ids.
  final List<NodeId> nodeIds;

  /// Monotonic runtime timestamp in milliseconds.
  final int timestampMs;

  /// Optional immutable metadata associated with the action.
  final Map<String, Object?>? payload;
}

/// Request from the engine to edit a text node at [position].
class EditTextRequested {
  /// Creates a text-edit request for app-owned editor UI.
  const EditTextRequested({
    required this.nodeId,
    required this.timestampMs,
    required this.position,
  });

  /// Target text node id.
  final NodeId nodeId;

  /// Monotonic runtime timestamp in milliseconds.
  final int timestampMs;

  /// Requested editor anchor position in view coordinates.
  final Offset position;
}

extension ActionCommittedDelta on ActionCommitted {
  /// Parses `payload.delta` into a [Transform2D] when present and valid.
  ///
  /// Returns `null` if payload does not contain a valid delta map.
  Transform2D? tryTransformDelta() {
    final payload = this.payload;
    if (payload == null) return null;
    final delta = payload['delta'];
    if (delta is! Map) return null;

    final map = <String, Object?>{};
    for (final entry in delta.entries) {
      final key = entry.key;
      if (key is! String) return null;
      map[key] = entry.value;
    }

    try {
      return Transform2D.fromJsonMap(map);
    } on ArgumentError {
      return null;
    }
  }

  /// Parses layer move metadata from the action payload.
  ///
  /// Expected schema: `{sourceLayerIndex: int, targetLayerIndex: int}`.
  ({int sourceLayerIndex, int targetLayerIndex})? tryMoveLayerIndices() {
    final payload = this.payload;
    if (payload == null) return null;

    int? tryInt(Object? value) {
      if (value is int) return value;
      if (value is num) {
        final asInt = value.toInt();
        if (value == asInt) return asInt;
      }
      return null;
    }

    final source = tryInt(payload['sourceLayerIndex']);
    final target = tryInt(payload['targetLayerIndex']);
    if (source == null || target == null) return null;
    return (sourceLayerIndex: source, targetLayerIndex: target);
  }

  /// Parses common draw style metadata from the action payload.
  ///
  /// Expected schema: `{tool: String, color: int, thickness: double}`.
  ({String tool, int colorArgb, double thickness})? tryDrawStyle() {
    final payload = this.payload;
    if (payload == null) return null;

    int? tryInt(Object? value) {
      if (value is int) return value;
      if (value is num) {
        final asInt = value.toInt();
        if (value == asInt) return asInt;
      }
      return null;
    }

    double? tryDouble(Object? value) {
      if (value is num) return value.toDouble();
      return null;
    }

    final tool = payload['tool'];
    if (tool is! String) return null;
    final colorArgb = tryInt(payload['color']);
    final thickness = tryDouble(payload['thickness']);
    if (colorArgb == null || thickness == null) return null;
    return (tool: tool, colorArgb: colorArgb, thickness: thickness);
  }

  /// Parses eraser metadata from the action payload.
  ///
  /// Expected schema: `{eraserThickness: double}`.
  double? tryEraserThickness() {
    final payload = this.payload;
    if (payload == null) return null;
    final thickness = payload['eraserThickness'];
    if (thickness is num) return thickness.toDouble();
    return null;
  }
}
